const Messages = {

    titles: {
        financial: 'Financeiro',
        family: 'Família Leron',
        login: 'E-mail',
        loginEnter: 'Entrar',
        createAccount: 'Registre-se',
        userOrPasswordWrong:'Usuário ou Senha incorreta!',
        register: 'Cadastro',
        back: 'Voltar',
        name: 'Nome',
        email: 'Email',
        password: 'Senha',
        comfirmPassword: 'Confirma Senha',
        sex: 'Sexo',
        cpf: 'CPF',
        userRegisterSucess: 'Conta criada com sucesso!',
        errorMessage: 'Algo deu errado!',
        add: 'Adicionar',
        permission: 'Permissão',
        addMember: 'Membro criado com sucesso!',
        registerMembers: 'Cadastro de Membros',
        addMembers: '+ Adicionar Membros',
        emptyList: 'Não há dados disponíveis',
        bank: "Banco",
        accountNumber: "Número da conta",
        owner: "Titular",
        card: "Cartão",
        cardName: "Nome Cartão",
        finalCard: "Final Cartão",
        modality: "Modalidade",
        dueDate: "Vencimento",
        closingDate: "Fechamento Fatura",
        addAccount: '+ Adicionar Conta',
        addCard: '+ Adicionar Cartão',
        registerBankData: 'Cadastro de Dados Bancários',
        infoTitleLogin: 'Bem-vindo ao Financeiro!',
        infoTextLogin: 'Seja o mestre das finanças da sua família em um só lugar. Com nosso sistema intuitivo, você pode rastrear despesas, definir metas e conquistar o controle total das suas finanças. Comece agora e construa um futuro financeiro sólido para sua família.',
        responsible: 'Responsável',
        account: 'Conta Bancária',
        accountBank: 'Conta',
        pointsProgram: 'Programa de Pontos',
        registerProgramPoint: 'Cadastro de Programa de pontos',
        program: 'Programa',
        addProgram: '+ Adicionar Programa',
        member: 'Membro',
        dataBank: 'Dados Bancários',
        points: 'Pontuação',
        currency: 'Moeda',
        point: 'Ponto',
        spent: 'Gasto',
        value: 'Valor Inicial',
        expirationDate: 'Data de expiração',
        typeOfScore: 'Tipo de Acúmulo',
        transfer: 'Transferir',
        transfer_: 'Transferência',
        addTransfer: '+ Transferência',
        origin: 'Origem',
        destiny: 'Destino',
        quantity: 'Quantidade',
        operation: 'Operação',
        bonus: 'Bonificação',
        percentage: 'Porcentagem',
        one: '1',
        totalMiles: 'Total Milhas',
        totalPoints: 'Total Pontos',
        totalActive: 'Programas Ativos',
        totalInactive: 'Programas Inativos',
        valuePrevius: 'Valor Previsto',
        pointsAndMiles: 'Pontos e Milhas',
        use: 'Utilizar',
        status: 'Status',
        usePoints: 'Utilizar Pontos/Milhas',
        groups: 'Grupos',
        registerGroups: 'Cadastro de Grupos',
        macroGroup: 'Grupo Macro',
        specificGroup: 'Grupo Específico',
        addGroup: '+ Adicionar G.Específico',
        exclusion: 'Excluir',
        score: 'Pontua',
        ownerOrigin: 'Titular Origem',
        ownerDestiny: 'Titular Destino',
        color: 'Cor *',
        currentValue: 'Valor',
        movementBank: "Movimentação Bancária",
        pay: "Pagar",
        receive: "Receber",
        receivedYear: "Receita Prevista Total",
        receivedMonth: "Receita Confirmada",
        quantityNotOk: "Receita Pendente",
        quantityOk: "Receita Aguardando",
        totalMoney: "Total Acumulado",
        totalAvailable: "Total Disponível",
        totalGoal: 'Total Meta',
        totalDollar: 'Total em Dólar',
        entrance: 'Receitas',
        registerEntrance: 'Cadastro de Receitas',
        addEntrance: '+ Adicionar Receita',
        source: 'Fonte',
        typeOfEntrance: 'Tipo',
        managementTypes: 'Gerenciamento - Tipos',
        description: 'Descrição',
        addTypeOfEntrance: '+ Tipo',
        salaryValue: 'Salário Líquido',
        frequency: 'Periodicidade',
        dayOf: 'Dia da Semana',
        dayOfMonth: 'Dia do mês',
        dayOfQui: 'Quinzena',
        initialDate: 'Data Inicial',
        finalDate: 'Data Final',
        monthReceive: 'Mês de Receber',
        dayReceive: 'Dia de Receber',
        year: 'Ano',
        month: 'Mês',
        date: 'Data',
        dateReceive: 'Data Recebimento *',
        paymentRefer: 'Período Referente',
        obs: 'Observação',
        copy: 'Copiar formulário anterior',
        registerExpense: 'Cadastro Despesa',
        expense: 'Despesas',
        local: 'Local',
        paymentForm: 'Forma de Pagamento',
        quantityPart: 'Quantidade de Parcelas',
        dateBuy: 'Data da Compra',
        addExpense: '+ Adicionar Despesa',
        hasFixed: 'Despesa Fixa',
        totalValue: 'Valor Total',
        registerMoney: 'Cadastro de Dinheiro',
        addMoney: '+ Dinheiro',
        money: 'Dinheiro',
        entityName: 'Nome Entidade',
        balance: 'Saldo',
        registerTickets: 'Cadastro de Vales',
        addTickets: '+ Adicionar Vale',
        ticket: 'Vale',
        receiveForm: 'Forma Recebimento',
        term: "Despesa Parcelada",
        dayPayment: "Dia Pagamento",
        monthPayment: "Mês Pagamento",
        external: 'Transferência Externa',
        accountOrigin: 'Conta Origem',
        accountDestiny: 'Conta Destino',
        dateTransfer: 'Data Transferência',
        bankOrigin: 'Banco Origem',
        bankDestiny: 'Banco Destino'
    },
    buttons: {},
    labels: {},
    messages: {
        notAllowedMoreThan: '*Não é permitido adicionar mais de 3 contas*',
        operationSuccess: 'Operação realizada com sucesso!',
        emailNotOk: '*E-mail incorreto*',
        requiredFields: 'Campos obrigatórios não preenchidos.',
        bankNameAlreadyExists: 'O nome do banco já existe.',
        duplicateAccountNumber: 'Número da conta já existe.',
        duplicateCardNumber: 'Número do cartão já existe.',
        programExists: 'Programa já existe.',
        invalidTransaction: 'Transação Inválida!',
        invalidDate: 'Data Inválida!',
        valueIsNull: 'Valor está vazio!',
        insufficientOrigin: 'Saldo de origem insuficiente!',
        insufficientDestiny: 'Saldo de destino insuficiente!',
        programIsEqual: "Programa de Origem não pode ser igual ao Pregrama de Destino!",
        zero: 'O valor 0 não é permitido!',
        macroNameExists: 'Grupo macro já existe!',
        specificNameExists: 'Grupo específico já existe!',
        nameExists: 'Membro já existe!',
        confirm: 'Tem certeza de que deseja continuar?',
        confirmExclusion: 'Ao excluir este Grupo Macro, todos os Grupos Específicos associados também serão permanentemente removidos.',
        userExists: 'Usuário já existe!',
        ownerEmpty: 'Titular não possui nenhum programa ativo!',
        insufficientBalance: "Saldo insuficiente!",
        duplicateNames: "Não é permitido nomes duplicados!",
        exclusionBank: "Ao excluir este banco, todas as contas, cartões, movimentações bancárias, receitas e despesas associadas também serão permanentemente removidos.",
        exclusionAccount: "Ao excluir esta conta, todos os cartões associados também serão permanentemente removidos.",
        ownerNotHaveAccount: "Não existem contas bancárias registradas com esta combinação titular x banco.",
        entranceNotStarted: "Não foi possível completar a operação. Receita não iniciada.",
        expenseInfo: 'Despesa fixa: irá se repetir todos os meses. Ex: Contas de água, luz, telefone.',
        paymentInfo: 'Ao salvar uma despesa com a forma de pagamento Débito, será debitado de sua conta o valor automaticamente.',
        moneyExists: 'Moeda para este usuário já existe!',
        exclusionTicket: 'Ao excluir este Vale, todas as movimentações bancárias, receitas e despesas associadas também serão permanentemente removidos.',
        ticketInfo: 'Tickets ou Vales alimentação',
        externalInfo: 'Trasferência para contas bancárias não registradas neste sistema.',
    },
    modals: {},
    toasts: {}


}

export {Messages}
