const Messages = {

    titles: {
        financial: 'Financeiro',
        family: 'Família Leron',
        login: 'E-mail',
        loginEnter: 'Entrar',
        createAccount: 'Registre-se',
        userOrPasswordWrong:'Usuário ou Senha incorreta!',
        register: 'Cadastro',
        back: 'Voltar',
        name: 'Nome',
        email: 'Email',
        password: 'Senha',
        comfirmPassword: 'Confirma Senha',
        sex: 'Sexo',
        cpf: 'CPF',
        userRegisterSucess: 'Conta criada com sucesso!',
        errorMessage: 'Algo deu errado!',
        nameExists: 'Membro já existe!',
        add: 'Adicionar',
        permission: 'Permissão',
        addMember: 'Membro criado com sucesso!',
        registerMembers: 'Cadastro de Membros',
        addMembers: '+ Adicionar Membros',
        emptyList: 'Não há dados disponíveis',
        bank: "Banco",
        accountNumber: "Número da conta",
        owner: "Titular",
        card: "Cartão",
        cardName: "Nome Cartão",
        finalCard: "Final Cartão",
        modality: "Modalidade",
        dueDate: "Vencimento",
        closingDate: "Fechamento Fatura",
        addAccount: '+ Adicionar Conta',
        addCard: '+ Adicionar Cartão',
        registerBankData: 'Cadastro de Dados Bancários',
        infoTitleLogin: 'Bem-vindo ao Financeiro!',
        infoTextLogin: 'Seja o mestre das finanças da sua família em um só lugar. Com nosso sistema intuitivo, você pode rastrear despesas, definir metas e conquistar o controle total das suas finanças. Comece agora e construa um futuro financeiro sólido para sua família.',
        responsible: 'Responsável',
        account: 'Conta Bancária',
        accountBank: 'Conta',
    },
    buttons: {},
    labels: {},
    messages: {
        notAllowedMoreThan: '*Não é permitido adicionar mais de 3 contas*',
        operationSuccess: 'Operação realizada com sucesso!',
        emailNotOk: '*E-mail incorreto*',
        requiredFields: 'Campos obrigatórios não preenchidos.',
        bankNameAlreadyExists: 'O nome do banco já existe.',
        duplicateAccountNumber: 'Número da conta já existe.',
        duplicateCardNumber: 'Número do cartão já existe.',
    },
    modals: {},
    toasts: {}


}

export {Messages}
