const Messages = {

    titles: {
        financial: 'Financeiro',
        family: 'Família Leron',
        login: 'E-mail',
        loginEnter: 'Entrar',
        createAccount: 'Registre-se',
        userOrPasswordWrong:'Usuário ou Senha incorreta!',
        register: 'Cadastro',
        back: 'Voltar',
        name: 'Nome',
        email: 'Email',
        password: 'Senha',
        comfirmPassword: 'Confirma Senha',
        sex: 'Sexo',
        cpf: 'CPF',
        userRegisterSucess: 'Conta criada com sucesso!',
        errorMessage: 'Algo deu errado!',
        add: 'Adicionar',
        permission: 'Permissão',
        addMember: 'Membro criado com sucesso!',
        registerMembers: 'Cadastro de Membros',
        addMembers: '+ Adicionar Membros',
        emptyList: 'Não há dados disponíveis',
        bank: "Banco",
        accountNumber: "Número da conta",
        owner: "Titular",
        card: "Cartão",
        cardName: "Nome Cartão",
        finalCard: "Final Cartão",
        modality: "Modalidade",
        dueDate: "Vencimento",
        closingDate: "Fechamento Fatura",
        addAccount: '+ Adicionar Conta',
        addCard: '+ Adicionar Cartão',
        registerBankData: 'Cadastro de Dados Bancários',
        infoTitleLogin: 'Bem-vindo ao Financeiro!',
        infoTextLogin: 'Seja o mestre das finanças da sua família em um só lugar. Com nosso sistema intuitivo, você pode rastrear despesas, definir metas e conquistar o controle total das suas finanças. Comece agora e construa um futuro financeiro sólido para sua família.',
        responsible: 'Responsável',
        account: 'Conta Bancária',
        accountBank: 'Conta',
        pointsProgram: 'Programa de Pontos',
        registerProgramPoint: 'Cadastro de Programa de pontos',
        program: 'Programa',
        addProgram: '+ Adicionar Programa',
        member: 'Membro',
        dataBank: 'Dados Bancários',
        points: 'Pontuação',
        currency: 'Moeda',
        point: 'Ponto',
        spent: 'Gasto',
        value: 'Valor Inicial',
        expirationDate: 'Data de expiração',
        typeOfScore: 'Tipo de Acúmulo',
        transfer: 'Transferir',
        transfer_: 'Transferência',
        addTransfer: '+ Transferência',
        origin: 'Origem',
        destiny: 'Destino',
        quantity: 'Quantidade',
        operation: 'Operação',
        bonus: 'Bonificação',
        percentage: 'Porcentagem',
        one: '1',
        totalMiles: 'Total Milhas',
        totalPoints: 'Total Pontos',
        totalActive: 'Programas Ativos',
        totalInactive: 'Programas Inativos',
        valuePrevius: 'Valor Previsto',
        pointsAndMiles: 'Pontos e Milhas',
        use: 'Utilizar',
        status: 'Status',
        usePoints: 'Utilizar Pontos/Milhas',
        groups: 'Grupos',
        registerGroups: 'Cadastro de Grupos',
        macroGroup: 'Grupo Macro',
        specificGroup: 'Grupo Específico',
        addGroup: 'Adicionar G.Específico'

    },
    buttons: {},
    labels: {},
    messages: {
        notAllowedMoreThan: '*Não é permitido adicionar mais de 3 contas*',
        operationSuccess: 'Operação realizada com sucesso!',
        emailNotOk: '*E-mail incorreto*',
        requiredFields: 'Campos obrigatórios não preenchidos.',
        bankNameAlreadyExists: 'O nome do banco já existe.',
        duplicateAccountNumber: 'Número da conta já existe.',
        duplicateCardNumber: 'Número do cartão já existe.',
        programExists: 'Programa já existe.',
        invalidTransaction: 'Transação Inválida!',
        invalidDate: 'Data Inválida!',
        valueIsNull: 'Valor está vazio!',
        insufficientOrigin: 'Saldo de origem insuficiente!',
        insufficientDestiny: 'Saldo de destino insuficiente!',
        programIsEqual: "Programa de Origem não pode ser igual ao Pregrama de Destino!",
        zero: 'O valor 0 não é permitido!',
        macroNameExists: 'Grupo macro já existe!',
        specificNameExists: 'Grupo específico já existe!',
        nameExists: 'Membro já existe!',
    },
    modals: {},
    toasts: {}


}

export {Messages}
